version: '3'
services:
  api_proxy_server:
    build: ./api_proxy_server
    ports:
      - "3001:3001"
    environment:
      - ANTHROPIC_API_KEY=api_key
      - CMS_ROUTE=http://host.docker.internal:3002
      - PORT=3001
  webserver:
    build:
      context: ./webserver
      args:
        # These args are given during build time
        CMS_ROUTE: http://host.docker.internal:3002
        REVALIDATE_TIME_SECS: 15
        AI_API: http://localhost:3001
    ports:
      - "3000:3000"
    environment:
      # These args are given during runtime
      - AI_API=http://localhost:3001
      - CMS_ROUTE=http://host.docker.internal:3002
      - REVALIDATE_TIME_SECS=15
