version: '3'
services:
# This makes the dockerised containers publicly accessible so that
# runtime fetch requests made by the webserver (in browser) reach
# the containers sequestered in the docker network through forwarding
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webserver
      - api_proxy_server
      - cms_server
# SERVERS
  api_proxy_server:
    build: ./api_proxy_server
    ports:
      - "3001:3001"
    environment:
      - ANTHROPIC_API_KEY=<YOUR API KEY> # ENTER AN API KEY HERE OR AI FUNCTIONALITY WON'T WORK
      - CMS_ROUTE=http://cms_server:3002
      - PORT=3001
  cms_server:
    build: ./cms_server
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATA_DIR=/app/data
    volumes:
      - ./cms_data:/app/data
  webserver:
    build:
      context: ./webserver
      args:
        CMS_ROUTE: http://host.docker.internal/cms
        REVALIDATE_TIME_SECS: 15
        AI_API: http://host.docker.internal/api
        VERSION: 1.5
    ports:
      - "3000:3000"
    environment:
      - AI_API=http://host.docker.internal/api
      - CMS_ROUTE=http://host.docker.internal/cms
      - REVALIDATE_TIME_SECS=15
      - VERSION=1.5