version: '3'
services:
  api_proxy_server:
    build: ./api_proxy_server
    ports:
      - "3001:3001"
    environment:
      - ANTHROPIC_API_KEY=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
      - CMS_ROUTE=http://cms_server:3002
      - PORT=3001
  cms_server:
    build: ./cms_server
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
  webserver:
    build: ./webserver
    ports:
      - "3000:3000"
    environment:
      - AI_API=http://api_proxy_server:3001
      - CMS_ROUTE=http://cms_server:3002
      - REVALIDATE_TIME_SECS=5
    depends_on:
      - api_proxy_server
      - cms_server
